### ISSUE TITLE
Hi! Some questions about the size of input.

### ISSUE THREAD

**Issue by wqz960** [jhaux/VUNet#1]
Thank you for your wonderful code!
1. Can you tell me the size of input, 128 or 256? Because of my bad network, it is slow to download the dataset to run it, can you tell it, please?
2. I have seen your config file, it seems that the size of input is 128, if I want to train vunet for the size of 256, how should I modify the network structure?
Thank you !!!

**Comment by jhaux** [comment]
Hi, sure, no problem!

1. The size is 256 by default, but you can change it by varying the config parameter `model_pars/spatial_size`
2. In the config, the comments are always above the parameters they describe. The `nf_max` parameter is set to 128, meaning, that during the encoding pass the generated features will have a depth of 128 max.

Does this solve you problem?

**Comment by wqz960** [comment]
Thank you for quick respond!
Now I am trying to train my dataset based on your code, Thank you!

**Comment by jhaux** [comment]
Glad to be of help!
Just as a follow up: I added code to download a super tiny (3.3MB) debug dataset. The downloader walks you through the process and lets you choose. All you have to do is change the `data_root` parameter to a new locations. You can do this by explicitly changing the `prjoti.yaml` config file or by passing `--data_root /your/path/here`. A third alternative is to set it to `None` and choose the path during the download process.
